---
'on':
  push:
    branches:
    - main
    - github-actions
    - setup-cosign
name: Publish to Docker Hub on push to main
jobs:
  Deploy_all_to_Docker_Hub:
    name: Deploy all to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
    - uses: actions/checkout@v2
    - name: Docker Hub Login
      uses: parkr/actions/docker-auth@main
      with:
        args: login
      env:
        DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
        DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
        DOCKER_REGISTRY_URL: docker.io
    - name: Publish airconnect
      uses: parkr/actions/docker-make@main
      with:
        args: publish-airconnect sign-airconnect
    - name: Publish aws-cli
      uses: parkr/actions/docker-make@main
      with:
        args: publish-aws-cli sign-aws-cli
    - name: Publish checkup
      uses: parkr/actions/docker-make@main
      with:
        args: publish-checkup sign-checkup
    - name: Publish curl
      uses: parkr/actions/docker-make@main
      with:
        args: publish-curl sign-curl
    - name: Publish git
      uses: parkr/actions/docker-make@main
      with:
        args: publish-git sign-git
    - name: Publish graphql-schema-linter
      uses: parkr/actions/docker-make@main
      with:
        args: publish-graphql-schema-linter sign-graphql-schema-linter
    - name: Publish html-proofer
      uses: parkr/actions/docker-make@main
      with:
        args: publish-html-proofer sign-html-proofer
    - name: Publish monicahq
      uses: parkr/actions/docker-make@main
      with:
        args: publish-monicahq sign-monicahq
    - name: Publish octodns
      uses: parkr/actions/docker-make@main
      with:
        args: publish-octodns sign-octodns
    - name: Publish puppet-lint
      uses: parkr/actions/docker-make@main
      with:
        args: publish-puppet-lint sign-puppet-lint
    - name: Publish rclone
      uses: parkr/actions/docker-make@main
      with:
        args: publish-rclone sign-rclone
    - name: Publish silence-but-for-error
      uses: parkr/actions/docker-make@main
      with:
        args: publish-silence-but-for-error sign-silence-but-for-error
    - name: Publish southwestcheckin
      uses: parkr/actions/docker-make@main
      with:
        args: publish-southwestcheckin sign-southwestcheckin
    - name: Docker Hub Logout
      uses: parkr/actions/docker-auth@main
      with:
        args: logout
      env:
        DOCKER_REGISTRY_URL: docker.io
