name: Build & test on push
'on':
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches:
      - main
      - github-actions
  workflow_dispatch: {}

jobs:
  Detect_projects:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.set-matrix.outputs.projects }}
    steps:
      - uses: actions/checkout@v6
      - id: set-matrix
        run: |
          PROJECTS=$(find * -maxdepth 1 -type d -exec test -f {}/VERSION \; -exec test -f {}/Dockerfile \; -print | grep -v 'homeassistant' | jq -R -s -c 'split("\n")[:-1]')
          echo "projects=${PROJECTS}" >> "$GITHUB_OUTPUT"

  Test:
    needs: Detect_projects
    name: Test ${{ matrix.project }}
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.Detect_projects.outputs.projects) }}
    steps:
      - uses: actions/checkout@v6
      - name: Test ${{ matrix.project }}
        uses: parkr/actions/docker-make@main
        with:
          args: test-${{ matrix.project }}
