---
'on': push
name: Build & test on push
jobs:
  Test checkup:
    name: Test checkup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test checkup
      uses: parkr/actions/docker-make@main
      with:
        args: test-checkup
  Test homeassistant:
    name: Test homeassistant
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test homeassistant
      uses: parkr/actions/docker-make@main
      with:
        args: test-homeassistant
  Test monicahq:
    name: Test monicahq
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test monicahq
      uses: parkr/actions/docker-make@main
      with:
        args: test-monicahq
  Test rclone:
    name: Test rclone
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test rclone
      uses: parkr/actions/docker-make@main
      with:
        args: test-rclone
  Test southwestcheckin:
    name: Test southwestcheckin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test southwestcheckin
      uses: parkr/actions/docker-make@main
      with:
        args: test-southwestcheckin
  Test octodns:
    name: Test octodns
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test octodns
      uses: parkr/actions/docker-make@main
      with:
        args: test-octodns
  Test silence-but-for-error:
    name: Test silence-but-for-error
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test silence-but-for-error
      uses: parkr/actions/docker-make@main
      with:
        args: test-silence-but-for-error
  Test curl:
    name: Test curl
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test curl
      uses: parkr/actions/docker-make@main
      with:
        args: test-curl
  Test airconnect:
    name: Test airconnect
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test airconnect
      uses: parkr/actions/docker-make@main
      with:
        args: test-airconnect
  Test aws-cli:
    name: Test aws-cli
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test aws-cli
      uses: parkr/actions/docker-make@main
      with:
        args: test-aws-cli
  Test graphql-schema-linter:
    name: Test graphql-schema-linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test graphql-schema-linter
      uses: parkr/actions/docker-make@main
      with:
        args: test-graphql-schema-linter
  Test git:
    name: Test git
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test git
      uses: parkr/actions/docker-make@main
      with:
        args: test-git
  Test puppet-lint:
    name: Test puppet-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test puppet-lint
      uses: parkr/actions/docker-make@main
      with:
        args: test-puppet-lint
