---
'on':
  push:
    branches:
    - main
    - github-actions
    - setup-cosign
name: Publish to GitHub Container Registry on push to main
jobs:
  Deploy_all_to_GitHub_Container_Registry:
    name: Deploy all to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Container Registry Login
      uses: parkr/actions/docker-auth@main
      with:
        args: login
      env:
        DOCKER_USERNAME: "${{ secrets.GPR_USERNAME }}"
        DOCKER_PASSWORD: "${{ secrets.GPR_PASSWORD }}"
        DOCKER_REGISTRY_URL: ghcr.io
    - name: Download cosign key
      run: echo "$COSIGN_KEY" > cosign.key
      shell: bash
      env:
        COSIGN_KEY: "${{secrets.COSIGN_KEY}}"
    - name: Publish airconnect to GitHub Container Registry
      uses: parkr/actions/docker-make@main
      with:
        args: publish-airconnect sign-airconnect -e NAMESPACE=ghcr.io/parkr
        cosign-password: "${{secrets.COSIGN_KEY_PASSPHRASE}}"
    - name: Publish aws-cli to GitHub Container Registry
      uses: parkr/actions/docker-make@main
      with:
        args: publish-aws-cli sign-aws-cli -e NAMESPACE=ghcr.io/parkr
        cosign-password: "${{secrets.COSIGN_KEY_PASSPHRASE}}"
    - name: Publish checkup to GitHub Container Registry
      uses: parkr/actions/docker-make@main
      with:
        args: publish-checkup sign-checkup -e NAMESPACE=ghcr.io/parkr
        cosign-password: "${{secrets.COSIGN_KEY_PASSPHRASE}}"
    - name: Publish curl to GitHub Container Registry
      uses: parkr/actions/docker-make@main
      with:
        args: publish-curl sign-curl -e NAMESPACE=ghcr.io/parkr
        cosign-password: "${{secrets.COSIGN_KEY_PASSPHRASE}}"
    - name: Publish git to GitHub Container Registry
      uses: parkr/actions/docker-make@main
      with:
        args: publish-git sign-git -e NAMESPACE=ghcr.io/parkr
        cosign-password: "${{secrets.COSIGN_KEY_PASSPHRASE}}"
    - name: Publish graphql-schema-linter to GitHub Container Registry
      uses: parkr/actions/docker-make@main
      with:
        args: publish-graphql-schema-linter sign-graphql-schema-linter -e NAMESPACE=ghcr.io/parkr
        cosign-password: "${{secrets.COSIGN_KEY_PASSPHRASE}}"
    - name: Publish html-proofer to GitHub Container Registry
      uses: parkr/actions/docker-make@main
      with:
        args: publish-html-proofer sign-html-proofer -e NAMESPACE=ghcr.io/parkr
        cosign-password: "${{secrets.COSIGN_KEY_PASSPHRASE}}"
    - name: Publish monicahq to GitHub Container Registry
      uses: parkr/actions/docker-make@main
      with:
        args: publish-monicahq sign-monicahq -e NAMESPACE=ghcr.io/parkr
        cosign-password: "${{secrets.COSIGN_KEY_PASSPHRASE}}"
    - name: Publish octodns to GitHub Container Registry
      uses: parkr/actions/docker-make@main
      with:
        args: publish-octodns sign-octodns -e NAMESPACE=ghcr.io/parkr
        cosign-password: "${{secrets.COSIGN_KEY_PASSPHRASE}}"
    - name: Publish puppet-lint to GitHub Container Registry
      uses: parkr/actions/docker-make@main
      with:
        args: publish-puppet-lint sign-puppet-lint -e NAMESPACE=ghcr.io/parkr
        cosign-password: "${{secrets.COSIGN_KEY_PASSPHRASE}}"
    - name: Publish rclone to GitHub Container Registry
      uses: parkr/actions/docker-make@main
      with:
        args: publish-rclone sign-rclone -e NAMESPACE=ghcr.io/parkr
        cosign-password: "${{secrets.COSIGN_KEY_PASSPHRASE}}"
    - name: Publish silence-but-for-error to GitHub Container Registry
      uses: parkr/actions/docker-make@main
      with:
        args: publish-silence-but-for-error sign-silence-but-for-error -e NAMESPACE=ghcr.io/parkr
        cosign-password: "${{secrets.COSIGN_KEY_PASSPHRASE}}"
    - name: Publish southwestcheckin to GitHub Container Registry
      uses: parkr/actions/docker-make@main
      with:
        args: publish-southwestcheckin sign-southwestcheckin -e NAMESPACE=ghcr.io/parkr
        cosign-password: "${{secrets.COSIGN_KEY_PASSPHRASE}}"
    - name: Delete cosign key
      run: rm $COSIGN_KEY
    - name: GitHub Container Registry Logout
      uses: parkr/actions/docker-auth@main
      with:
        args: logout
      env:
        DOCKER_REGISTRY_URL: ghcr.io
