---
'on': push
name: Build & test on push
jobs:
  Test_airconnect:
    name: Test airconnect
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
    - uses: actions/checkout@v2
    - name: Test airconnect
      uses: parkr/actions/docker-make@main
      with:
        args: test-airconnect
  Test_aws-cli:
    name: Test aws-cli
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
    - uses: actions/checkout@v2
    - name: Test aws-cli
      uses: parkr/actions/docker-make@main
      with:
        args: test-aws-cli
  Test_checkup:
    name: Test checkup
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
    - uses: actions/checkout@v2
    - name: Test checkup
      uses: parkr/actions/docker-make@main
      with:
        args: test-checkup
  Test_curl:
    name: Test curl
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
    - uses: actions/checkout@v2
    - name: Test curl
      uses: parkr/actions/docker-make@main
      with:
        args: test-curl
  Test_git:
    name: Test git
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
    - uses: actions/checkout@v2
    - name: Test git
      uses: parkr/actions/docker-make@main
      with:
        args: test-git
  Test_graphql-schema-linter:
    name: Test graphql-schema-linter
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
    - uses: actions/checkout@v2
    - name: Test graphql-schema-linter
      uses: parkr/actions/docker-make@main
      with:
        args: test-graphql-schema-linter
  Test_html-proofer:
    name: Test html-proofer
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
    - uses: actions/checkout@v2
    - name: Test html-proofer
      uses: parkr/actions/docker-make@main
      with:
        args: test-html-proofer
  Test_monicahq:
    name: Test monicahq
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
    - uses: actions/checkout@v2
    - name: Test monicahq
      uses: parkr/actions/docker-make@main
      with:
        args: test-monicahq
  Test_octodns:
    name: Test octodns
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
    - uses: actions/checkout@v2
    - name: Test octodns
      uses: parkr/actions/docker-make@main
      with:
        args: test-octodns
  Test_puppet-lint:
    name: Test puppet-lint
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
    - uses: actions/checkout@v2
    - name: Test puppet-lint
      uses: parkr/actions/docker-make@main
      with:
        args: test-puppet-lint
  Test_rclone:
    name: Test rclone
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
    - uses: actions/checkout@v2
    - name: Test rclone
      uses: parkr/actions/docker-make@main
      with:
        args: test-rclone
  Test_silence-but-for-error:
    name: Test silence-but-for-error
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
    - uses: actions/checkout@v2
    - name: Test silence-but-for-error
      uses: parkr/actions/docker-make@main
      with:
        args: test-silence-but-for-error
  Test_southwestcheckin:
    name: Test southwestcheckin
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
    - uses: actions/checkout@v2
    - name: Test southwestcheckin
      uses: parkr/actions/docker-make@main
      with:
        args: test-southwestcheckin
