on:
  push:
    branches:
      - main
      - docker-login-action

name: Publish to Docker Hub on push to main
jobs:
  deployAllToDockerHub:
    name: Deploy all to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Login
      uses: parkr/actions/docker-auth@main
      with:
        args: login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
    - name: Publish southwestcheckin
      uses: parkr/actions/docker-make@main
      with:
        args: publish-southwestcheckin
    - name: Publish silence-but-for-error
      uses: parkr/actions/docker-make@main
      with:
        args: publish-silence-but-for-error
    - name: Publish rclone
      uses: parkr/actions/docker-make@main
      with:
        args: publish-rclone
    - name: Publish puppet-lint
      uses: parkr/actions/docker-make@main
      with:
        args: publish-puppet-lint
    - name: Publish octodns
      uses: parkr/actions/docker-make@main
      with:
        args: publish-octodns
    - name: Publish monicahq
      uses: parkr/actions/docker-make@main
      with:
        args: publish-monicahq
    - name: Publish homeassistant
      uses: parkr/actions/docker-make@main
      with:
        args: publish-homeassistant
    - name: Publish git
      uses: parkr/actions/docker-make@main
      with:
        args: publish-git
    - name: Publish curl
      uses: parkr/actions/docker-make@main
      with:
        args: publish-curl
    - name: Publish checkup
      uses: parkr/actions/docker-make@main
      with:
        args: publish-checkup
    - name: Publish aws-cli
      uses: parkr/actions/docker-make@main
      with:
        args: publish-aws-cli
    - name: Publish airconnect
      uses: parkr/actions/docker-make@main
      with:
        args: publish-airconnect
    - name: Docker Logout
      uses: parkr/actions/docker-auth@main
      with:
        args: logout
      env:
        DOCKER_REGISTRY_URL: docker.io
