on:
 schedule:
   - cron: 0 0 * * *
 push:
   branches:
     - update-automatically

name: Automatic Version Updates
jobs:
 release:
   name: rclone
   runs-on: ubuntu-latest
   steps:
     - name: Update rclone version
       uses: technote-space/create-pr-action@v2
       with:
         EXECUTE_COMMANDS: |
           bash rclone/latest_version.sh
         COMMIT_MESSAGE: 'update rclone version'
         COMMIT_NAME: 'GitHub Actions'
         COMMIT_EMAIL: 'actions@github.com'
         PR_BRANCH_NAME: 'actions-rclone-version-update-${PR_ID}'
         PR_TITLE: 'Update rclone version'
         PR_BODY: 'A new version of rclone is available.'
         PR_BRANCH_PREFIX: 'update-automatically'
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
