---
'on':
  schedule:
  - cron: 0 0 * * *
  push:
    branches:
    - update-automatically
name: Automatic Version Updates
jobs:
  Update_monicahq_version:
    runs-on: ubuntu-latest
    steps:
    - name: Update monicahq version
      uses: technote-space/create-pr-action@v2
      with:
        EXECUTE_COMMANDS: make update-monicahq
        COMMIT_MESSAGE: Update monicahq version
        COMMIT_NAME: GitHub Actions
        COMMIT_EMAIL: actions@github.com
        PR_BRANCH_NAME: version-update-monicahq-${PR_ID}
        PR_TITLE: Update monicahq version
        PR_BODY: A new version of monicahq is available. cc @parkr
        PR_BRANCH_PREFIX: update-automatically-
  Update_rclone_version:
    runs-on: ubuntu-latest
    steps:
    - name: Update rclone version
      uses: technote-space/create-pr-action@v2
      with:
        EXECUTE_COMMANDS: make update-rclone
        COMMIT_MESSAGE: Update rclone version
        COMMIT_NAME: GitHub Actions
        COMMIT_EMAIL: actions@github.com
        PR_BRANCH_NAME: version-update-rclone-${PR_ID}
        PR_TITLE: Update rclone version
        PR_BODY: A new version of rclone is available. cc @parkr
        PR_BRANCH_PREFIX: update-automatically-
