---
'on':
  schedule:
  - cron: 0 0 * * *
  push:
    branches:
    - update-automatically
name: Automatic Version Updates
jobs:
  Update_airconnect_version:
    runs-on: ubuntu-latest
    steps:
    - name: Update airconnect version
      uses: technote-space/create-pr-action@v2
      with:
        EXECUTE_COMMANDS: make update-airconnect
        COMMIT_MESSAGE: Update airconnect version
        COMMIT_NAME: GitHub Actions
        COMMIT_EMAIL: actions@github.com
        PR_BRANCH_NAME: version-update-airconnect-${PR_ID}
        PR_TITLE: Update airconnect version
        PR_BODY: A new version of airconnect is available. cc @parkr
        PR_BRANCH_PREFIX: update-automatically-
  Update_checkup_version:
    runs-on: ubuntu-latest
    steps:
    - name: Update checkup version
      uses: technote-space/create-pr-action@v2
      with:
        EXECUTE_COMMANDS: make update-checkup
        COMMIT_MESSAGE: Update checkup version
        COMMIT_NAME: GitHub Actions
        COMMIT_EMAIL: actions@github.com
        PR_BRANCH_NAME: version-update-checkup-${PR_ID}
        PR_TITLE: Update checkup version
        PR_BODY: A new version of checkup is available. cc @parkr
        PR_BRANCH_PREFIX: update-automatically-
  Update_graphql-schema-linter_version:
    runs-on: ubuntu-latest
    steps:
    - name: Update graphql-schema-linter version
      uses: technote-space/create-pr-action@v2
      with:
        EXECUTE_COMMANDS: make update-graphql-schema-linter
        COMMIT_MESSAGE: Update graphql-schema-linter version
        COMMIT_NAME: GitHub Actions
        COMMIT_EMAIL: actions@github.com
        PR_BRANCH_NAME: version-update-graphql-schema-linter-${PR_ID}
        PR_TITLE: Update graphql-schema-linter version
        PR_BODY: A new version of graphql-schema-linter is available. cc @parkr
        PR_BRANCH_PREFIX: update-automatically-
  Update_html-proofer_version:
    runs-on: ubuntu-latest
    steps:
    - name: Update html-proofer version
      uses: technote-space/create-pr-action@v2
      with:
        EXECUTE_COMMANDS: make update-html-proofer
        COMMIT_MESSAGE: Update html-proofer version
        COMMIT_NAME: GitHub Actions
        COMMIT_EMAIL: actions@github.com
        PR_BRANCH_NAME: version-update-html-proofer-${PR_ID}
        PR_TITLE: Update html-proofer version
        PR_BODY: A new version of html-proofer is available. cc @parkr
        PR_BRANCH_PREFIX: update-automatically-
  Update_monicahq_version:
    runs-on: ubuntu-latest
    steps:
    - name: Update monicahq version
      uses: technote-space/create-pr-action@v2
      with:
        EXECUTE_COMMANDS: make update-monicahq
        COMMIT_MESSAGE: Update monicahq version
        COMMIT_NAME: GitHub Actions
        COMMIT_EMAIL: actions@github.com
        PR_BRANCH_NAME: version-update-monicahq-${PR_ID}
        PR_TITLE: Update monicahq version
        PR_BODY: A new version of monicahq is available. cc @parkr
        PR_BRANCH_PREFIX: update-automatically-
  Update_puppet-lint_version:
    runs-on: ubuntu-latest
    steps:
    - name: Update puppet-lint version
      uses: technote-space/create-pr-action@v2
      with:
        EXECUTE_COMMANDS: make update-puppet-lint
        COMMIT_MESSAGE: Update puppet-lint version
        COMMIT_NAME: GitHub Actions
        COMMIT_EMAIL: actions@github.com
        PR_BRANCH_NAME: version-update-puppet-lint-${PR_ID}
        PR_TITLE: Update puppet-lint version
        PR_BODY: A new version of puppet-lint is available. cc @parkr
        PR_BRANCH_PREFIX: update-automatically-
  Update_rclone_version:
    runs-on: ubuntu-latest
    steps:
    - name: Update rclone version
      uses: technote-space/create-pr-action@v2
      with:
        EXECUTE_COMMANDS: make update-rclone
        COMMIT_MESSAGE: Update rclone version
        COMMIT_NAME: GitHub Actions
        COMMIT_EMAIL: actions@github.com
        PR_BRANCH_NAME: version-update-rclone-${PR_ID}
        PR_TITLE: Update rclone version
        PR_BODY: A new version of rclone is available. cc @parkr
        PR_BRANCH_PREFIX: update-automatically-
  Update_teslamate-abrp_version:
    runs-on: ubuntu-latest
    steps:
    - name: Update teslamate-abrp version
      uses: technote-space/create-pr-action@v2
      with:
        EXECUTE_COMMANDS: make update-teslamate-abrp
        COMMIT_MESSAGE: Update teslamate-abrp version
        COMMIT_NAME: GitHub Actions
        COMMIT_EMAIL: actions@github.com
        PR_BRANCH_NAME: version-update-teslamate-abrp-${PR_ID}
        PR_TITLE: Update teslamate-abrp version
        PR_BODY: A new version of teslamate-abrp is available. cc @parkr
        PR_BRANCH_PREFIX: update-automatically-
