---
'on':
  schedule:
  - cron: 0 0 * * *
  push:
    branches:
    - update-automatically
    - update-automatically-*
  workflow_dispatch: {}
name: Automatic Version Updates
jobs:
  Find_outdated_apps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      apps: "${{ steps.outdated_apps.outputs.apps }}"
    steps:
    - uses: actions/checkout@v6
    - name: Find outdated apps
      id: outdated_apps
      run: echo "apps=$(script/outdated-apps --json)" >> "$GITHUB_OUTPUT"
  Update_outdated_apps:
    needs:
    - Find_outdated_apps
    if: "${{ needs.Find_outdated_apps.outputs.apps != '{}' }}"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix: "${{ fromJSON(needs.Find_outdated_apps.outputs.apps).include }}"
    steps:
    - name: Update ${{ matrix.app }} version
      uses: technote-space/create-pr-action@v2
      with:
        EXECUTE_COMMANDS: make update-${{ matrix.app }}
        COMMIT_MESSAGE: Update ${{ matrix.app }} version
        COMMIT_NAME: GitHub Actions
        COMMIT_EMAIL: actions@github.com
        PR_BRANCH_NAME: "${{ matrix.app }}"
        PR_BRANCH_PREFIX: update-automatically-
        PR_TITLE: Update ${{ matrix.app }} version
        PR_BODY: A new version of ${{ matrix.app }} is available. cc @parkr
